HTTP/1.0 503 Service Unavailable
Cache-Control: no-cache
Connection: close
Content-Type: text/html

<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8" />
        <title>Immich loading</title>
        <style>
            body {
                background-color: #070707;
                color: #e4e2e2;
                font-family: Verdana, Geneva, Tahoma, sans-serif
            }

            main {
                margin: auto;
                padding: 2em;
                width: 600px;
            }

            a, a:visited {
                color: rgb(158, 158, 196);
            }
            
            h1 {
                color: #cecece;
                border-bottom: 1px solid #9e9e9e;
            }

            .backend-status > div {
                margin-bottom: 0.4em;
                padding: 1em;
                border-radius: 0.8em;
                background-color: #2c2c2c;
            }

            .backend-status > div.fail {
                background: repeating-linear-gradient(
                    45deg,
                    rgba(255, 0, 0, 0.4),
                    rgba(255, 0, 0, 0.4) 10px,
                    rgba(255, 0, 0, 0.35) 10px,
                    rgba(255, 0, 0, 0.35) 20px
                );
            }

            .backend-status > div.okay {
                background: repeating-linear-gradient(
                    45deg,
                    rgba(0, 255, 0, 0.4),
                    rgba(0, 255, 0, 0.4) 10px,
                    rgba(0, 255, 0, 0.35) 10px,
                    rgba(0, 255, 0, 0.35) 20px
                );
            }

            .backend-status > div.unset::before {
                content: '⏳';
                margin-right: 0.4em;
            }

            .backend-status > div.okay::before {
                content: '✅';
                margin-right: 0.4em;
            }

            .backend-status > div.fail::before {
                content: '⛔';
                margin-right: 0.4em;
            }

            footer {
                padding: 0.4em;
                margin-top: 1em;
            }
        </style>
    </head>
    <body>
        <main>
            <h1>Immich loading ...</h1>

            <div class="backend-status">
                <div id="backend-be_server" class="unset">
                    Immich Server
                </div>
                <div id="backend-be_ml" class="unset">
                    Machine Learning
                </div>
                <div id="backend-be_postgres" class="unset">
                    Postgres (Relational Database)
                </div>
                <div id="backend-be_redis" class="unset">
                    Redis (In-memory key-value database)
                </div>
                <div id="backend-acme" class="unset">
                    ACME Challenge (Used by Let's Encrypt to issue a TLS certificate)
                </div>
                <div id="backend-stats" class="unset">
                    HAProxy Stats
                </div>
            </div>

            <footer>
                You see this page because Immich Web is not ready. Give it a minute to get ready.
                You can inspect the <a href="/haproxy">HAProxy stats</a> page for more information.
                The page should reload automatically when everything is ready.
            </footer>
        </main>

        <script>
            function do_request() {
                const request = new Request("/haproxy/;csv")
                fetch(request).then((response) => {
                    if (response.status === 200) {
                        return response.text()
                    }
                }).then((data) => {
                    lines = data.split("\n")
                    down_backends = 0
                    lines.forEach(line => {
                        ld = line.split(",")
                        if (ld[1] == "BACKEND") {
                            if (ld[17] == "UP") {
                                document.querySelector("#backend-"+ld[0]).className = "okay"
                            } else {
                                document.querySelector("#backend-"+ld[0]).className = "fail"
                                down_backends = down_backends + 1
                            }
                        }

                    });
                    
                    console.log(down_backends)
                    if (down_backends < 1) {
                        location.reload();
                    }

                    setTimeout(do_request, 1000)
                }).catch(error => {
                    setTimeout(do_request, 10000)
                })

            }

            setTimeout(do_request, 500)
        </script>
    </body>
</html>
