name: immich-distribution-libvips
base: core20
version: 8.14.5-dist2
summary: libvips packaged for Immich Distribution
description: |
  libvips packaged for Immich Distribution, this is not intended to be consumed directly.
architectures:
  - amd64

grade: stable
confinement: strict

apps:
  vips:
    command: usr/bin/vips

layout:
  /usr/etc/ImageMagick-7:
    symlink: $SNAP/usr/etc/ImageMagick-7
  /usr/lib/ImageMagick-7.1.1:
    symlink: $SNAP/usr/lib/ImageMagick-7.1.1

parts:
  libvips:
    plugin: meson
    meson-version: "1.2.1"
    meson-parameters:
      - --buildtype=release
      - --prefix=/usr
      - --libdir=lib
      - --default-library=static
    source: https://github.com/libvips/libvips/releases/download/v8.14.5/vips-8.14.5.tar.xz
    source-checksum: "sha256/90374e9f6fbd5657b5faf306cacda20658d6144d385316b59b865bc1a487b68d"
    build-packages:
      - libfftw3-dev
      - libopenexr-dev
      - libgsf-1-dev
      - libglib2.0-dev
      - liborc-dev
      - libopenslide-dev
      - libmatio-dev
      - libwebp-dev
      - libjpeg-turbo8-dev
      - libexpat1-dev
      - libexif-dev
      - libtiff5-dev
      - libcfitsio-dev
      - libpoppler-glib-dev
      - librsvg2-dev
      - libpango1.0-dev
      - libopenjp2-7-dev
      - libimagequant-dev
      - libgirepository1.0-dev
      - liblqr-1-0-dev
      - libheif-dev
      - libtiff-dev
      - libltdl-dev
    after:
      - cgif
      - imagemagick
    stage-packages:
      - libaec0
      - libasn1-8-heimdal
      - libbrotli1
      - libcairo-gobject2
      - libcfitsio8
      - libcurl3-gnutls
      - libexif12
      - libfftw3-double3
      - libgdk-pixbuf2.0-0
      - libgsf-1-114
      - libgssapi3-heimdal
      - libhcrypto4-heimdal
      - libhdf5-103
      - libheimbase1-heimdal
      - libheimntlm0-heimdal
      - libhx509-5-heimdal
      - libimagequant0
      - libkrb5-26-heimdal
      - libldap-2.4-2
      - libmatio9
      - libnghttp2-14
      - libnspr4
      - libnss3
      - libopenslide0
      - liborc-0.4-0
      - libpoppler-glib8
      - libpoppler97
      - libpsl5
      - libroken18-heimdal
      - librsvg2-2
      - librtmp1
      - libsasl2-2
      - libssh-4
      - libsz2
      - libwind0-heimdal

  cgif:
    plugin: meson
    meson-version: "1.2.1"
    source: https://github.com/dloebl/cgif.git
    source-tag: "V0.3.2"
    organize:
      usr/local: usr

  imagemagick:
    plugin: make
    source: https://github.com/ImageMagick/ImageMagick/archive/7.1.1-17.tar.gz
    source-checksum: "sha256/8f7840103f710312a50a6dd6a2722f189139c0226607b16af7c33f96bcf3cebd"
    override-build: |
      ./configure --with-modules --enable-static=yes --with-x=no --with-raw=yes --prefix=/usr
      snapcraftctl build
    build-packages:
      - libltdl-dev
      - libbz2-dev
      - libdjvulibre-dev
      - libexif-dev
      - libfftw3-dev
      - libfontconfig1-dev
      - libfreetype6-dev
      - libjpeg-dev
      - liblcms2-dev
      - liblqr-1-0-dev
      - liblzma-dev
      - libopenexr-dev
      - libpango1.0-dev
      - libperl-dev
      - libpng-dev
      - librsvg2-bin
      - librsvg2-dev
      - libtiff-dev
      - libwebp-dev
      - libwmf-dev
      - libx11-dev
      - libxext-dev
      - libxml2-dev
      - libxt-dev
      - zlib1g-dev
      - libheif-dev
      - libzstd-dev
      - wget
    stage-packages:
      - libcairo2
      - libdatrie1
      - libde265-0
      - libdjvulibre21
      - libfontconfig1
      - libfreetype6
      - libfribidi0
      - libgomp1
      - libgraphite2-3
      - libharfbuzz0b
      - libheif1
      - libicu66
      - libilmbase24
      - libjbig0
      - libjpeg-turbo8
      - liblcms2-2
      - liblqr-1-0
      - libltdl7
      - libnuma1
      - libopenexr24
      - libopenjp2-7
      - libpango-1.0-0
      - libpangocairo-1.0-0
      - libpangoft2-1.0-0
      - libpixman-1-0
      - libpng16-16
      - libthai0
      - libtiff5
      - libwebp6
      - libwebpdemux2
      - libwebpmux3
      - libwmf0.2-7
      - libx11-6
      - libx265-179
      - libxau6
      - libxcb-render0
      - libxcb-shm0
      - libxcb1
      - libxdmcp6
      - libxext6
      - libxml2
      - libxrender1
    stage:
      - -usr/share/apport
      - -usr/share/djvu
      - -usr/share/docs
      - -usr/share/doc
      - -usr/share/lintian
      - -usr/share/man
      - -usr/share/X11
    after:
      - libraw

  libraw:
    plugin: autotools
    source: https://github.com/libraw/libraw/archive/0.21.1.tar.gz
    source-checksum: "sha256/b63d7ffa43463f74afcc02f9083048c231349b41cc9255dec0840cf8a67b52e0"
    autotools-configure-parameters:
      - --disable-examples
      - --prefix=/usr
      - --enable-jpeg
      - --enable-zlib
    override-build: |
      autoreconf --install
      snapcraftctl build
    build-packages:
      - zlib1g-dev
      - libjpeg8-dev
      - pkg-config
    stage-packages:
      - libgomp1
      - libjpeg-turbo8
      - liblcms2-2
    stage:
      - -usr/share
