name: immich-distribution-typesense
base: core20
version: 0.24.1-dist1
summary: Typesense packaged for Immich Distribution
description: |
  Typesense packaged for Immich Distribution, this is not intended to be consumed directly.
architectures:
  - amd64

grade: stable
confinement: strict

parts:
  typesense:
    source: https://dl.typesense.org/releases/0.24.1/typesense-server-0.24.1-linux-amd64.tar.gz
    plugin: dump
    organize:
      typesense-server: bin/typesense-server
    stage:
      - bin
