name: immich-distribution-ffmpeg
base: core20
version: 6.0-dist2
summary: ffmpeg packaged for Immich Distribution
description: |
  ffmpeg packaged for Immich Distribution, this is not intended to be consumed directly.
architectures:
  - amd64

grade: stable
confinement: strict

parts:
  ffmpeg:
    plugin: dump
    # These builds are linked from the official ffmpeg site, so I assume they are safe.
    # It's a little annoying that there is not a stable URL, this link will be updated in the future and
    # the checksum will change... when that happens select the same release from "old-releases".
    source: https://johnvansickle.com/ffmpeg/releases/ffmpeg-release-amd64-static.tar.xz
    source-checksum: md5/8a34e2ab52b72777a8dcd3ff5defbcd8
    override-build: |
      mkdir -p $SNAPCRAFT_PART_INSTALL/bin
      cp $SNAPCRAFT_PART_SRC/ffmpeg $SNAPCRAFT_PART_INSTALL/bin
      cp $SNAPCRAFT_PART_SRC/ffprobe $SNAPCRAFT_PART_INSTALL/bin
