name: Bug Report
description: Have you found something wrong with Immich, submit a bug report.
title: "Please provide a good descriptive title"
labels: ["bug"]
assignees: ["nsg"]
body:
  - type: markdown
    attributes:
      value: |
        ## What's a bug?
        A bug is an error, flaw or fault in the design or operation that causes it to produce an incorrect or unexpected result, or to behave in unintended ways. For feature requests, support questions or general issues please [select an apropiate issue type](https://github.com/nsg/immich-distribution/issues/new/choose).

  - type: checkboxes
    id: upstream
    attributes:
      label: Docker Compose
      description: |
        The official (upstream) Immich installation is distributed via [docker-compose](https://immich.app/docs/install/docker-compose). Have you tried docker-compose.yml to see if this is an upstream problem, or is unique to this package (Immich Distribution)?.
      options:
        - label: This is an Immich Distribution specific bug

  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: Also tell us, what did you expect to happen?
      placeholder: Tell us what you see!
      value: "A well written text is easier for me to understand, and fix quickly."
    validations:
      required: true
