name: Bug Report
description: Have you found something wrong with Immich, submit a bug report.
title: "Please provide a good descriptive title"
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        ## What's a bug?
        A bug is an error, flaw or fault in the design or operation that causes
        it to produce an incorrect or unexpected result, or to behave in
        unintended ways.

  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: Also tell us, what did you expect to happen?
      placeholder: Tell us what you see!
      value: "A bug happened!"
    validations:
      required: true
