name: New version
description: Report the release of a new Immich version
title: "Immich X.Y.Z released / Immich CLI X.Y.Z released"
labels: ["enhancement"]
assignees: ["nsg"]
body:
  - type: dropdown
    id: software
    attributes:
      label: Software
      description: What software has a new version?
      options:
        - Immich
        - Immich CLI
        - Something else
    validations:
      required: true

  - type: textarea
    id: message
    attributes:
      label: Message
      description: Explain what to update, what version is released?
      placeholder: Immich version X.Y.Z is released
    validations:
      required: true

  - type: markdown
    attributes:
      value: |
        ## Thank you!
        Thank you for using the software. Keep an eye on this issue for updates or additional questions.
