name: New version
description: Report the release of a new Immich version
title: "Immich X.Y released"
labels: ["enhancement", "new-version"]
assignees: ["nsg"]
body:
  - type: textarea
    id: message
    attributes:
      label: Message
      description: Explain what to update, what version is released?
      placeholder: Immich version X.Y is released
    validations:
      required: true

  - type: markdown
    attributes:
      value: |
        ## Thank you!
        Thank you for using the software. Keep an eye on this issue for updates or additional questions.
