name: immich-distribution-haproxy
base: core20
adopt-info: haproxy
summary: HAProxy packaged for Immich Distribution
description: |
  HAProxy packaged for Immich Distribution, this is not intended to be consumed directly.
architectures:
  - amd64

grade: stable
confinement: strict

parts:
  haproxy:
    source: http://git.haproxy.org/git/haproxy-2.6.git
    source-tag: v2.6.15
    plugin: make
    override-build: |
      snapcraftctl set-version "$(git describe --tags)-dist1"
      snapcraftctl build
    make-parameters:
      - TARGET=linux-glibc
      - USE_OPENSSL=1
      - USE_ZLIB=1
      - USE_PCRE=1
    build-packages:
      - build-essential
      - libssl-dev
      - libpcre3-dev
      - libz-dev
    organize:
      usr/local/sbin/haproxy: bin/haproxy
    stage:
      - -usr
