name: immich-distribution-lego
base: core20
adopt-info: lego
summary: Lego packaged for Immich Distribution
description: |
  Lego packaged for Immich Distribution, this is not intended to be consumed directly.
architectures:
  - amd64

grade: stable
confinement: strict

parts:
  lego:
    source: https://github.com/go-acme/lego.git
    source-tag: v4.10.2
    plugin: go
    build-environment:
      - GO111MODULE: "on"
    override-build: |
      snapcraftctl set-version "$(git describe --tags)-dist1"
      make build
      mkdir -p $SNAPCRAFT_PART_INSTALL/bin
      cp dist/lego $SNAPCRAFT_PART_INSTALL/bin
