#!/bin/bash

. $SNAP/bin/load-env

export PYTHONPATH="$SNAP/app/machine-learning/python-packages"
export LD_PRELOAD="$SNAP/usr/local/lib/libmimalloc.so.2"

echo "Launching machine-learning service using python version: $(python3 --version)"
echo "PYTHONPATH: $PYTHONPATH"
echo "LD_PRELOAD: $LD_PRELOAD"

cd $SNAP/app/machine-learning
python3 $SNAP/bin/gunicorn app.main:app \
	-k app.config.CustomUvicornWorker \
 	-w $MACHINE_LEARNING_WORKERS \
 	-b $MACHINE_LEARNING_HOST:$MACHINE_LEARNING_PORT \
	-t $MACHINE_LEARNING_WORKER_TIMEOUT \
	--log-config-json log_conf.json \
	--graceful-timeout 0
