name: Install snap
description: Download a built snap artifact and install it dangerously.

inputs:
  artifact-name:
    description: Name of the snap artifact to download.
    required: false
    default: development-snap-package

runs:
  using: composite
  steps:
    - name: Download snap artifact
      uses: actions/download-artifact@v4
      with:
        name: ${{ inputs.artifact-name }}

    - name: Install snap package
      shell: bash
      run: sudo snap install --dangerous *.snap
