site_name: Immich Distribution
repo_url: https://github.com/nsg/immich-distribution
edit_uri: edit/master/docs/docs/
nav:
  - About: index.md
  - News: news/index.md
  - Installation: install.md
  - Configuration:
    - Introduction: configuration/index.md
    - configuration/security.md
    - HTTPS: configuration/https.md
    - Library:
      - Default Library: configuration/library/default.md
      - External Library: configuration/library/external.md
      - How To: configuration/library/howto.md
    - configuration/backup-restore.md
    - configuration/postgres.md
    - configuration/haproxy.md
    - configuration/sync.md
  - Contribute:
    - Upgrade: build/upgrade.md
    - Patches: build/patches.md
    - Tests: build/tests.md

theme:
  name: material
  palette:
    primary: custom
  logo: assets/immich-dist-greyscale.png
  favicon: assets/immich-dist-greyscale.png
  icon:
    repo: fontawesome/brands/github
    edit: material/source-repository
  features:
    - navigation.tabs
    - navigation.expand
    - navigation.top
    - navigation.indexes
    - search.suggest
    - search.highlight
    - content.action.edit
    - content.code.copy
    - content.code.annotate
plugins:
  - tags
  - search
  - blog:
      blog_dir: news
extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/nsg/immich-distribution
      name: Project page at GitHub
markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - tables
  - attr_list
  - md_in_html
  - footnotes
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
extra_css:
  - css/extra.css
