site_name: Immich Distribution
repo_url: https://github.com/nsg/immich-distribution
edit_uri: edit/master/docs/docs/
nav:
  - About: about.md
  - News: [news/index.md]
  - Installation: install.md
  - Configuration:
    - Introduction: configuration/index.md
    - configuration/security.md
    - HTTPS: configuration/https.md
    - Library:
      - Storage Locations: configuration/library/storage.md
      - External Library: configuration/library/external.md
      - How To: configuration/library/howto.md
    - configuration/backup-restore.md
    - configuration/postgres.md
    - configuration/haproxy.md
    - configuration/sync.md
    - Immich Admin Extensions: configuration/cli-administration.md
    - Notifications: configuration/notifications.md
    - configuration/metrics.md
  - Contribute:
    - Upgrade: build/upgrade.md
    - Tests: build/tests.md
    - Statistics: build/statistics.md
    - Package Dependencies: build/dependencies.md

theme:
  name: material
  palette:
    primary: custom
  logo: assets/immich-dist.png
  favicon: assets/immich-dist.png
  icon:
    repo: fontawesome/brands/github
    edit: material/source-repository
  features:
    - navigation.tabs
    - navigation.expand
    - navigation.top
    - navigation.indexes
    - search.suggest
    - search.highlight
    - content.action.edit
    - content.code.copy
    - content.code.annotate
plugins:
  - tags
  - search
  - blog:
      blog_dir: news
      blog_toc: true
hooks:
  - snapstore_versions.py
extra:
  generator: false  # Manually written in the copyright notice
copyright: >
  Immich Distribution is an independent community project that packages the software in a snap package.
  This project is not affiliated with the upstream <strong><a href="https://immich.app">Immich project</a></strong>,
  its developers, or <strong><a href="https://futo.org">FUTO</a></strong>.
  For more information, please refer to the <strong><a href="/">about page</a></strong>.
  Website made with <strong><a href="https://squidfunk.github.io/mkdocs-material/">Material for MkDocs</a></strong>.
  Also check out the projects <strong><a href="https://github.com/nsg/immich-distribution">GitHub repository</a></strong>.
markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - tables
  - attr_list
  - md_in_html
  - footnotes
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
extra_css:
  - css/extra.css
