name: immich-distribution
title: Immich Distribution
base: core20
adopt-info: server
summary: This is an Immich Distribution packaged by the community.
description: |
  This is an Immich Distribution packaged inside a snap package.
  The package is inspired of the official Immich images. It will be
  similar, but not identical with the official Docker-based
  installation. It will ship the same software, but with limited
  customability. Extra tools are included, they should be
  non-intrusive and you can ignore them if you prefer.

  **More information:** https://github.com/nsg/immich-distribution

  This is **NOT** an official package. For support, open an issue on
  the link above.
grade: stable
confinement: strict
architectures:
  - amd64
assumes:
  - command-chain

system-usernames:
  snap_daemon: shared

layout:
  $SNAP/usr/src/app/.reverse-geocoding-dump:
    symlink: $SNAP_COMMON/reverse-geocoding-dump
  $SNAP/usr/src/app/upload:
    symlink: $SNAP_COMMON/upload
  $SNAP/usr/src/ml/upload:
    symlink: $SNAP_COMMON/upload

apps:
  psql:
    command: bin/psql
    plugs:
      - network

  postgres:
    command: bin/postgres
    daemon: simple
    restart-delay: 10s
    plugs:
      - network-bind

  redis-server:
    command: bin/redis-server $SNAP/etc/redis.conf
    daemon: simple
    restart-delay: 10s
    plugs:
      - network-bind

  typesense:
    command: bin/typesense
    daemon: simple
    restart-delay: 10s
    plugs:
      - network-bind

  immich-server:
    command: bin/immich-server
    daemon: simple
    restart-delay: 10s
    after:
      - redis-server
      - postgres
      - typesense
    plugs:
      - network-bind
      - network

  immich-microservices:
    command: bin/immich-microservices
    daemon: simple
    restart-delay: 10s
    after:
      - redis-server
      - postgres
      - immich-server
    plugs:
      - network-bind
      - network

  immich-web:
    command: bin/immich-web
    daemon: simple
    restart-delay: 10s
    after:
      - redis-server
      - postgres
      - immich-server
    plugs:
      - network-bind
      - network

  cli:
    command: bin/immich-cli
    plugs:
      - network

  immich-machine-learning:
    command: bin/immich-machine-learning
    daemon: simple
    restart-delay: 10s
    after:
      - redis-server
      - postgres
      - immich-server
    plugs:
      - network-bind
      - network

  haproxy:
    command-chain:
      - bin/haproxy-chain
    command: bin/haproxy -W -f $SNAP/etc/haproxy.cfg -p $SNAP_DATA/haproxy.pid
    daemon: simple
    plugs:
      - network-bind
      - network

  sync-import-watch:
    command: bin/sync-import-watch
    daemon: simple
    restart-delay: 10s
    timer: "00:00-24:00/1"
    after:
      - immich-server
    plugs:
      - network

  sync-removed-fs:
    command: bin/sync-removed-watch
    daemon: simple
    restart-delay: 10s
    after:
      - immich-server
    plugs:
      - network

  sync-created-fs:
    command: bin/sync-created-watch
    daemon: simple
    restart-delay: 10s
    after:
      - immich-server
    plugs:
      - network

  sync-database-watch:
    command: bin/sync-database-watch
    daemon: simple
    restart-delay: 10s
    after:
      - immich-server
    plugs:
      - network

  backup:
    command: bin/backup

  import:
    command: bin/import

  lets-encrypt:
    command: bin/acme-init
    plugs:
      - network
      - network-bind

  acme:
    command: bin/acme-service
    daemon: simple
    restart-delay: 60s
    timer: "00:00-24:00/2"
    plugs:
      - network
      - network-bind

parts:
  node:
    plugin: nil
    override-build: |
      if [ ! -f "$SNAPCRAFT_PART_INSTALL/bin/node" ]; then
        curl -s https://nodejs.org/dist/v18.16.0/node-v18.16.0-linux-x64.tar.xz \
        | tar xJf - -C "$SNAPCRAFT_PART_INSTALL" --no-same-owner --strip-components=1
      fi

  ffmpeg:
    plugin: nil
    stage-packages:
      - ffmpeg
      - libglu1-mesa
      - freeglut3
      - libpulse0
      - libslang2
    prime:
      - -usr/share/doc
      - -usr/share/man

  # "npm run build" builds: server, microservices, cli
  server:
    plugin: npm
    npm-node-version: "18.16.0"
    source: https://github.com/immich-app/immich.git
    source-tag: v1.57.1
    source-subdir: server
    override-build: |
      snapcraftctl set-version "$(git describe --tags)-dist1"
      cd server
      npm ci
      npm run build
      npm prune --omit=dev --omit=optional
      mkdir -p $SNAPCRAFT_PART_INSTALL/usr/src/app
      cp -r node_modules $SNAPCRAFT_PART_INSTALL/usr/src/app
      cp -r dist $SNAPCRAFT_PART_INSTALL/usr/src/app
      cp -r bin $SNAPCRAFT_PART_INSTALL/usr/src/app
      cp start-server.sh start-microservices.sh $SNAPCRAFT_PART_INSTALL/usr/src/app
    stage-packages:
      - libc-ares2
      - libicu66
      - libnghttp2-14
      - libnode64
      - libuv1
      - libvips
    after:
      - node

  web:
    plugin: npm
    npm-node-version: "18.16.0"
    source: https://github.com/immich-app/immich.git
    source-tag: v1.57.1
    source-subdir: web
    override-build: |
      patch -p0 -i $SNAPCRAFT_PART_SRC/../../patches/src/001-version-announcement-box.patch -d $SNAPCRAFT_PART_BUILD
      cd web
      npm ci
      npm run build
      npm prune --omit=dev
      mkdir -p $SNAPCRAFT_PART_INSTALL/usr/src/web
      cp -r node_modules $SNAPCRAFT_PART_INSTALL/usr/src/web
      cp -r build $SNAPCRAFT_PART_INSTALL/usr/src/web
      cp package.json package-lock.json $SNAPCRAFT_PART_INSTALL/usr/src/web
    after:
      - node
      - patches

  machine-learning:
    plugin: python
    source: https://github.com/immich-app/immich.git
    source-tag: v1.57.1
    source-subdir: machine-learning
    build-environment:
      - SNAPCRAFT_PYTHON_VENV_INTERP_PATH: /root/parts/machine-learning/install/bin/python3
    override-build: |
      snapcraftctl build
      pip install torch --index-url https://download.pytorch.org/whl/cpu
      pip install transformers tqdm numpy scikit-learn scipy nltk sentencepiece fastapi Pillow uvicorn[standard]
      pip install --no-deps sentence-transformers
      pip install insightface onnxruntime
      mkdir -p $SNAPCRAFT_PART_INSTALL/usr/src/ml
      cp -r machine-learning/src $SNAPCRAFT_PART_INSTALL/usr/src/ml
    stage-packages:
      - libgomp1

  cli:
    plugin: npm
    npm-node-version: "18.16.0"
    source: https://github.com/immich-app/CLI.git
    source-tag: v0.36.0
    override-build: |
      npm install
      npm run build
      mkdir -p $SNAPCRAFT_PART_INSTALL/usr/src/cli
      cp -r node_modules $SNAPCRAFT_PART_INSTALL/usr/src/cli
      cp -r bin $SNAPCRAFT_PART_INSTALL/usr/src/cli
      cp package.json package-lock.json $SNAPCRAFT_PART_INSTALL/usr/src/cli
    after:
      - node

  redis:
    source: https://github.com/redis/redis.git
    source-tag: 7.0.9
    plugin: make
    build-packages:
      - pkg-config
    override-build: |
      make
      make PREFIX=$SNAPCRAFT_PART_INSTALL install
    prime:
      - bin/redis-server

  postgres:
    source: https://ftp.postgresql.org/pub/source/v15.2/postgresql-15.2.tar.bz2
    plugin: make
    build-packages:
      - libreadline-dev
      - zlib1g-dev
      - uuid-dev
    override-build: |
      ./configure --enable-thread-safety --with-uuid=e2fs --with-gnu-ld
      snapcraftctl build
      cd contrib
      make
      make install DESTDIR=$SNAPCRAFT_PART_INSTALL

  typesense:
    source: https://dl.typesense.org/releases/0.24.0/typesense-server-0.24.0-linux-amd64.tar.gz
    plugin: dump
    organize:
      typesense-server: bin/typesense-server

  haproxy:
    source: http://git.haproxy.org/git/haproxy-2.6.git
    source-tag: v2.6.10
    plugin: make
    make-parameters:
      - TARGET=linux-glibc
      - USE_OPENSSL=1
      - USE_ZLIB=1
      - USE_PCRE=1
    build-packages:
      - build-essential
      - libssl-dev
      - libpcre3-dev
      - libz-dev
    stage:
      - -usr/local/doc
      - -usr/local/share
    organize:
      usr/local/sbin/haproxy: bin/haproxy

  lego:
    source: https://github.com/go-acme/lego.git
    source-tag: v4.10.2
    plugin: go
    build-environment:
      - GO111MODULE: "on"
    override-build: |
      make build
      mkdir -p $SNAPCRAFT_PART_INSTALL/bin
      cp dist/lego $SNAPCRAFT_PART_INSTALL/bin

  scripts:
    source: src
    plugin: dump
    stage-packages:
      - util-linux
      - fswatch
      - curl
      - jq
      - xz-utils

  patches:
    source: patches
    plugin: dump
    stage: []
