name: immich-distribution
title: Immich Distribution
base: core20
adopt-info: server
summary: This is an Immich Distribution packaged by the community.
description: |
  This is an Immich Distribution packaged inside a snap package.
  The package is inspired of the official Immich images. It will be
  similar, but not identical with the official Docker-based
  installation. It will ship the same software, but with limited
  customability. Extra tools are included, they should be
  non-intrusive and you can ignore them if you prefer.

  **More information:** https://github.com/nsg/immich-distribution

  This is **NOT** an official package. For support, open an issue on
  the link above.
grade: stable
confinement: strict
architectures:
  - amd64
assumes:
  - command-chain

system-usernames:
  snap_daemon: shared

layout:
  $SNAP/usr/src/app/.reverse-geocoding-dump:
    symlink: $SNAP_COMMON/reverse-geocoding-dump
  $SNAP/usr/src/app/upload:
    symlink: $SNAP_COMMON/upload
  /usr/etc/ImageMagick-7:
    symlink: $SNAP/usr/etc/ImageMagick-7
  /usr/lib/ImageMagick-7.1.1:
    symlink: $SNAP/usr/lib/ImageMagick-7.1.1

apps:
  psql:
    command: bin/psql
    plugs:
      - network

  postgres:
    command: bin/postgres
    daemon: simple
    restart-delay: 10s
    plugs:
      - network-bind

  redis-server:
    command: bin/redis-server $SNAP/etc/redis.conf
    daemon: simple
    restart-delay: 10s
    plugs:
      - network-bind

  typesense:
    command: bin/typesense
    daemon: simple
    restart-delay: 10s
    plugs:
      - network-bind

  immich-server:
    command: bin/immich-server
    daemon: simple
    restart-delay: 10s
    after:
      - redis-server
      - postgres
      - typesense
    plugs:
      - network-bind
      - network

  immich-microservices:
    command: bin/immich-microservices
    daemon: simple
    restart-delay: 10s
    after:
      - redis-server
      - postgres
      - immich-server
    plugs:
      - network-bind
      - network

  immich-web:
    command: bin/immich-web
    daemon: simple
    restart-delay: 10s
    after:
      - redis-server
      - postgres
      - immich-server
    plugs:
      - network-bind
      - network

  cli:
    command: bin/immich-cli
    plugs:
      - network

  immich-machine-learning:
    command: bin/immich-machine-learning
    daemon: simple
    restart-delay: 10s
    after:
      - redis-server
      - postgres
      - immich-server
    plugs:
      - network-bind
      - network

  haproxy:
    command-chain:
      - bin/haproxy-chain
    command: bin/haproxy -W -f $SNAP/etc/haproxy.cfg -p $SNAP_DATA/haproxy.pid
    daemon: simple
    plugs:
      - network-bind
      - network

  sync-import-watch:
    command: bin/sync-import-watch
    daemon: simple
    restart-delay: 10s
    timer: "00:00-24:00/1"
    after:
      - immich-server
    plugs:
      - network

  sync-service:
    command: bin/sync-service.sh
    daemon: simple
    restart-delay: 10s
    after:
      - immich-server
    plugs:
      - network

  backup:
    command: bin/backup

  import:
    command: bin/import

  lets-encrypt:
    command: bin/acme-init
    plugs:
      - network
      - network-bind

  acme:
    command: bin/acme-service
    daemon: simple
    restart-delay: 60s
    timer: "00:00-24:00/2"
    plugs:
      - network
      - network-bind

parts:
  ffmpeg:
    plugin: dump
    # These builds are linked from the official ffmpeg site, so I assume they are safe.
    # It's a little annoying that there is not a stable URL, this link will be updated in the future and
    # the checksum will change... when that happens select the same release from "old-releases".
    source: https://johnvansickle.com/ffmpeg/releases/ffmpeg-release-amd64-static.tar.xz
    source-checksum: md5/bef7015ca2fd7f19057cad0262d970d2
    override-build: |
      mkdir -p $SNAPCRAFT_PART_INSTALL/bin
      cp $SNAPCRAFT_PART_SRC/ffmpeg $SNAPCRAFT_PART_INSTALL/bin
      cp $SNAPCRAFT_PART_SRC/ffprobe $SNAPCRAFT_PART_INSTALL/bin

  # "npm run build" builds: server, microservices, cli
  server:
    plugin: npm
    npm-node-version: "18.16.0"
    source: https://github.com/immich-app/immich.git
    source-tag: v1.81.1
    source-subdir: server
    override-build: |
      snapcraftctl set-version "$(git describe --tags)-dist1"
      cd server
      npm ci
      npm run build
      npm prune --omit=dev --omit=optional
      mkdir -p $SNAPCRAFT_PART_INSTALL/usr/src/app
      cp -r node_modules $SNAPCRAFT_PART_INSTALL/usr/src/app
      cp -r dist $SNAPCRAFT_PART_INSTALL/usr/src/app
      cp -r bin $SNAPCRAFT_PART_INSTALL/usr/src/app
      cp package.json $SNAPCRAFT_PART_INSTALL/usr/src/app
      cp start-server.sh start-microservices.sh $SNAPCRAFT_PART_INSTALL/usr/src/app
    after:
      - dependencies

  web:
    plugin: npm
    npm-node-version: "18.16.0"
    source: https://github.com/immich-app/immich.git
    source-tag: v1.81.1
    source-subdir: web
    override-build: |
      patch -p0 -i $SNAPCRAFT_PART_SRC/../../patches/src/001-version-announcement-box.patch -d $SNAPCRAFT_PART_BUILD
      cd web
      npm ci
      npm run build
      npm prune --omit=dev
      mkdir -p $SNAPCRAFT_PART_INSTALL/usr/src/web
      cp -r node_modules $SNAPCRAFT_PART_INSTALL/usr/src/web
      cp -r build $SNAPCRAFT_PART_INSTALL/usr/src/web
      cp package.json package-lock.json $SNAPCRAFT_PART_INSTALL/usr/src/web
    after:
      - dependencies
      - patches

  machine-learning:
    plugin: make
    source: parts/machine-learning
    build-packages:
      - git
    stage-packages:
      - libgomp1
    after:
      - dependencies

  cli:
    plugin: npm
    npm-node-version: "18.16.0"
    source: https://github.com/immich-app/CLI.git
    source-tag: v0.41.0
    override-build: |
      npm install
      npm run build
      mkdir -p $SNAPCRAFT_PART_INSTALL/usr/src/cli
      cp -r node_modules $SNAPCRAFT_PART_INSTALL/usr/src/cli
      cp -r bin $SNAPCRAFT_PART_INSTALL/usr/src/cli
      cp package.json package-lock.json $SNAPCRAFT_PART_INSTALL/usr/src/cli
    after:
      - dependencies

  dependencies:
    plugin: nil
    stage-snaps:
      - immich-distribution-redis/latest/stable
      - immich-distribution-postgres/latest/stable
      - immich-distribution-typesense/latest/stable
      - immich-distribution-haproxy/latest/stable
      - immich-distribution-lego/latest/stable
      - immich-distribution-libvips/latest/stable
      - immich-distribution-node/latest/stable
      - immich-distribution-python/latest/stable
      - immich-distribution-mimalloc/latest/stable

  scripts:
    source: src
    plugin: dump
    stage-packages:
      - util-linux
      - fswatch
      - curl
      - jq
      - xz-utils

  sync:
    plugin: nil
    override-build:
      ../../dependencies/install/usr/local/bin/python3 ../../dependencies/install/usr/local/bin/pip3 install watchfiles requests psycopg2-binary --target $SNAPCRAFT_PART_INSTALL/opt/pipsyncenv
    after:
      - dependencies

  patches:
    source: patches
    plugin: dump
    stage: []
