name: Issue and PR automations

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0,6,12,18 * * *"
  push:
    branches:
      - master

concurrency:
  group: "bump"
  cancel-in-progress: true

permissions:
  contents: write
  issues: write
  pull-requests: write

jobs:
  tracking-issue:
    name: Tracking Issue
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Create Tracking Issue
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          ./workflows/tracking-issue.sh

      - name: Update Tracking Issues
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          ./workflows/update-tracking-issue.sh

  create-pr-version-bump:
    name: Create PR Version Bump
    runs-on: ubuntu-latest
    needs: tracking-issue

    steps:
      - uses: actions/checkout@v3
        with:
          ssh-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Install uv
        uses: astral-sh/setup-uv@v5

      - name: Create PR Version Bump
        env:
          GH_TOKEN: ${{ github.token }}
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        run: |
          git config --global user.name "Github Action Automation"
          git config --global user.email "nsg@users.noreply.github.com"
          ./workflows/create-pr-version-bump.sh
