name: Automatically bump version

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0,6,12,18 * * *"
  pull_request:

concurrency:
  group: "bump"
  cancel-in-progress: true

permissions:
  contents: write
  pull-requests: write

jobs:
  bump-version:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Bump version
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          git config --global user.name "Github Action Automation"
          git config --global user.email "nsg@users.noreply.github.com"

          OLD_VERSION=$(cat VERSION)
          make version-update
          NEW_VERSION=$(cat VERSION)
          BRANCH_NAME="bump-$NEW_VERSION"
          REMOTE_URL=$(git remote get-url origin)

          if git ls-remote --exit-code "$REMOTE_URL" "refs/heads/$BRANCH_NAME" >/dev/null 2>&1; then
            echo "Branch $BRANCH_NAME already exists."
            exit 0
          fi

          if [ "$OLD_VERSION" != "$NEW_VERSION" ]; then
            git checkout -b $BRANCH_NAME
            git add .
            git commit -m "Bump version to $NEW_VERSION"
            git push -u origin $BRANCH_NAME

            gh pr create \
              --base master \
              --assignee=nsg \
              --title "Bump $NEW_VERSION" \
              --body 'Created by Github action'
          fi
