name: Automatically bump version

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0,6,12,18 * * *"

concurrency:
  group: "bump"
  cancel-in-progress: true

permissions:
  contents: write
  issues: write
  pull-requests: write

jobs:
  bump-version:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      # A GitHub Action can't trigger another GitHub Actions Events
      # using the GH_TOKEN. So we need to use a SSH key to trigger
      # the push event in system-tests.yaml for our pull request.
      - name: Add SSH key to SSH Agent
        env:
            SSH_AUTH_SOCK: /tmp/ssh_agent.sock
        run: |
            mkdir -p /home/runner/.ssh
            echo "${{ secrets.SSH_PRIVATE_KEY }}" > /home/runner/.ssh/github_actions
            chmod 600 /home/runner/.ssh/github_actions
            ssh-agent -a $SSH_AUTH_SOCK > /dev/null	
            ssh-add /home/runner/.ssh/github_actions

      - name: Bump version
        env:
          GH_TOKEN: ${{ github.token }}
          SSH_AUTH_SOCK: /tmp/ssh_agent.sock
        run: |
          git config --global user.name "Github Action Automation"
          git config --global user.email "nsg@users.noreply.github.com"
          ./auto-bump.sh
