name: Build and release snap package to edge channel

on:
  push:
    branches:
      - 'master'
    paths-ignore:
      - 'docs/**'
      - '*.md'
      - 'LICENSE'

  workflow_dispatch:

permissions:
  contents: read

jobs:
  build-snap:
    name: Build Snap Package
    uses: ./.github/workflows/build-snap.yaml
    with:
      artifact-name: release-snap-package

  run-tests:
    name: Asset Processing Tests
    needs: build-snap
    uses: ./.github/workflows/snap-asset-processing-tests.yaml
    with:
      snap-artifact-name: release-snap-package

  release:
    name: Release Snap Package
    runs-on: ubuntu-latest
    needs: [build-snap, run-tests]

    steps:
      - name: Download snap artifact
        uses: actions/download-artifact@v4
        with:
          name: release-snap-package

      - name: Expand snap artifact name
        id: snap-path
        run: echo "SNAP_PATH=$(echo *.snap)" >> $GITHUB_OUTPUT

      - name: Upload snap package to edge channel
        uses: snapcore/action-publish@v1
        env:
          SNAPCRAFT_STORE_CREDENTIALS: ${{ secrets.STORE_LOGIN }}
        with:
          snap: ${{ steps.snap-path.outputs.SNAP_PATH }}
          release: edge
