name: Build a dependency

on:
  workflow_call:
    inputs:
      dependency:
        required: true
        type: string

jobs:
  build:
    name: Build ${{ inputs.dependency }}
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - uses: actions/cache@v3
        id: cache
        with:
          key: ${{ hashFiles(format('dependencies/', inputs.dependency, '/**')) }}-key1
          path: |
            dependencies/**/*.snap

      - name: Build snap package
        uses: snapcore/action-build@v1
        if: steps.cache.outputs.cache-hit != 'true'
        id: build
        with:
          path: dependencies/${{ inputs.dependency }}

      - name: Save snap package as an artifact
        uses: actions/upload-artifact@v3
        with:
          name: ${{ inputs.dependency }}
          if-no-files-found: error
          path: |
            dependencies/**/*.snap
