name: Build and deploy documentation

on:
  push:
    branches: [ "master" ]
  workflow_dispatch:
  schedule:
    - cron: "0 12 * * *"

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - uses: actions/checkout@v4
      - uses: actions/configure-pages@v5

      - name: Install snapcraft
        run: |
          sudo snap install snapcraft --classic

      - name: Install jq
        run: |
          sudo apt-get update
          sudo apt-get install -y jq

      - name: Build site
        env:
          SNAP_METRICS_KEY: ${{ secrets.SNAP_METRICS_KEY }}
        run: |
          cd docs
          make build

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: 'docs/site/build-out'

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
