name: Build and deploy documentation

on:
  push:
    branches: [ "master" ]
  workflow_dispatch:
  schedule:
    - cron: "0 12 * * *"

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - uses: actions/checkout@v3
      - uses: actions/configure-pages@v3

      - name: Install Poetry
        run: |
          python3 -m venv venv
          venv/bin/pip install poetry
          
      - name: Install deps for pillow
        run: sudo apt-get install -y libtiff5-dev libjpeg8-dev libopenjp2-7-dev zlib1g-dev libfreetype6-dev liblcms2-dev libwebp-dev tcl8.6-dev tk8.6-dev python3-tk libharfbuzz-dev libfribidi-dev libxcb1-dev

      - name: Install dependencies for mkdocs-material
        run: |
          cd docs
          ../venv/bin/poetry install

      - name: Build site
        run: |
          cd docs
          ../venv/bin/poetry run mkdocs build

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v1
        with:
          path: 'docs/site'

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v2
