name: Run System Tests on Edge Snap

on:
  push:
    branches:
      - 'bump/**'
    paths-ignore:
      - 'docs/**'
      - '*.md'
      - 'LICENSE'

  pull_request:
    branches: [ "master" ]
    paths-ignore:
      - 'docs/**'
      - '*.md'
      - 'LICENSE'

  workflow_dispatch:

jobs:
  build-and-test-snap:
    runs-on: ubuntu-latest

    services:
      selenium:
        image: selenium/standalone-chrome:latest
        options: --shm-size=2gb
        ports:
          - 4444:4444

    steps:
      - uses: actions/checkout@v3

      - name: Install package
        run: |
          sudo snap install --edge immich-distribution

      - name: Install requirements
        run: pip install -r tests/requirements.txt

      - name: Run Selenium Tests
        run: make ci -C tests

      - name: Upload test report
        uses: actions/upload-artifact@v3
        if: always()
        with:
          name: selenium-test-report
          path: |
            tests/report.html
            tests/assets/style.css
            tests/latest_logs
