name: Weekly Upgrade Blocking Test

on:
  schedule:
    # Run every Sunday at 02:00 UTC
    - cron: '0 2 * * 0'
  
  workflow_dispatch:
    # Allow manual triggering

jobs:
  upgrade-blocking-test:
    name: Test Upgrade Blocking Mechanism
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: TEST | Run Upgrade Blocking Tests
        run: make test-upgrade-blocking -C tests

      - name: Upload test results on failure
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: upgrade-blocking-test-logs
          retention-days: 7
          path: |
            tests/upgrade_output.log
            tests/*.log
