#!/bin/bash

# Add this file to ignore the checks in this hook
[ -e "$SNAP_COMMON/no-pre-refresh-hook" ] && exit 0

. $SNAP/bin/load-env

# Backup the database before the migration from pgvecto.rs to VectorChord
if ! $SNAP/backup -d -n "pgvectors"; then
    echo "Failed to create and validate database backup during pre-refresh."
    exit 1
fi

exit 0
